name: ESLint

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Specify your desired Node.js version

      - name: Install ESLint
        run: npm install eslint -g

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint --prefix elfin_adapter
