name: Lint JavaScript

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint JavaScript
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Run EsLint Node.js Linter
        run: |
          cd elfin_adapter
          npm install
          npm run lint


